[package]
name = "pdf_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pdf-extract = "0.7.7"
polars = { version = "0.39.2", features = ["json"] }
regex = "1.10.4"
serde = "1.0.202"
serde_json = "1.0.117"
